### PR TITLE
Refactor Form 8 a little bit

### PR DESCRIPTION
**Pull request by shanear**

### CODE REVIEW

**Comment by shanear** [comment]
This pull is mixed with #237, check that one out first

**Comment by orischwartz** [comment]
Any way to unstack the commits? I forget how to do it but Paul knows

**Comment by orischwartz** [comment]
I'm spectacularly out of date on this but is this still something that we want merged? It has stacked commits from another PR and cannot be updated against master so it would need some cleanup first. Reassign if you want pursue.

**Comment by shanear** [comment]
I'm gonna kill this.

**Pull request closed without merging**
