### PR TITLE
Add in a Help page. Close: #53

### PR DESCRIPTION
**Pull request by paultag**
Initial cut at a Help page, just start to put some basic things out in
the codebase, so that we can iterate on this later.

This is a straight HTML port of the Document Kavi wrote up. Needs more
work. This is just to get it into VCS.

Thanks, @KHarshawat

### CODE REVIEW

**Comment by paultag** [comment]
cc @KHarshawat

**Comment by shanear** [comment]
welp,

https://github.com/department-of-veterans-affairs/caseflow-certification/pull/90

:(

**Comment by shanear** [comment]
@paultag just add a feature spec (per my pull) as a sanity and accessibility check.

**Comment by paultag** [comment]
@shanear ouch, looks like we had a few bugs about the help page - I count 3 :(

**Pull request merged**
