### PR TITLE
Rake task for marking and cleaning up old form 8 files

### LINKED ISSUE #56: Determine Form 8 clean up policy
https://github.com/department-of-veterans-affairs/caseflow/issues/10

### PR DESCRIPTION
**Pull request by shanear**
just need to add it to the cron scheduler in deploy

fixes #56

### CODE REVIEW

**Comment by orischwartz** [comment]
Cool. 

* Any reason why we can't list files in `tmp/pdfs` and delete anything with a creation time < some threshold? Why the `clean-after-` file? 
* This would have to scheduled via cron, correct? Is there anyway to schedule a periodic task in ruby that would e.g., wake up a thread to do this every hour? This way it's more self-contained and we only have to deploy/monitor one production application instead of two.

**Comment by shanear** [comment]
creation date is handled differently on different OS's and since we have windows, OSx, and linux between the machines that run Caseflow, i tried to make something that didn't rely on the OS.

You could do this via sleep. but that doesn't seem good. I was thinking just get a cron job to run this rake task twice a day. I researched it a little and this seems to be the common practice (running a rake task on a cron)

**Comment by orischwartz** [comment]
OK fair enough. How do we invoke this as a rake task? Is there a file missing from `lib/tasks?`

We also need to add a corresponding change to deployment repo and schedule this as a rake task.

**Comment by shanear** [comment]
your right, i forgot to commit the rake task :hankey:

agree on the deployment modification, i was treating this as a prereq though. will do that once this solution clears.

**Comment by orischwartz** [comment]
ok, good to go then :+1: 

See referenced issue in deployment repo for part 2

**Pull request closed without merging**
