### PR TITLE
rollover logs every MB, retain 10

### PR DESCRIPTION
**Pull request by orischwartz**
This should be deployed to a non-prod environment and verified before promoting to production.

### CODE REVIEW

**Comment by shanear** [comment]
welp, this was easier than I thought it would be lol.

**Comment by paultag** [comment]
:us:

**Comment by orischwartz** [comment]
Actually one small improvement a grizzled Ruby-veteran like @shanear could have caught--`alias :megabyte :megabytes` ...

 more readable `1.megabyte` instead of `1.megabytes`.

**Comment by shanear** [comment]
@orischwartz, you're becoming a rubyist :joy:

**Comment by orischwartz** [comment]
Verified in dev:

```console
$ ls -lht /app/caseflow/src/log/
total 3.7M
-rw-r-xr-x. 1 caseflow service  930 Mar 23 10:24 production.log
-rw-rwxr-x. 1 caseflow service 3.7M Mar 23 10:16 production.log.0
```

**Comment by orischwartz** [comment]
This doesn't seem to work...maybe it rolls over restarts? 

```
$ ls -lhS /app/caseflow/src/log/
total 47M
-rw-rwxr-x. 1 caseflow service  38M Apr 11 09:56 production.log
```

**Pull request merged**
