### PR TITLE
Add connect_vbms and integrate it with document loading

### PR DESCRIPTION
**Pull request by shanear**

### CODE REVIEW

**Comment by shanear** [comment]
We're commiting the entire source of vbms_connect, because we need the built java code. But its far from ideal.

Waiting on the ruby-version of the encryption code.

**Comment by shanear** [comment]
@orischwartz can you give this one a looksies

**Comment by orischwartz** [comment]
@shanear Looking now...yeah I was wondering why we needed all those SOAP definition files...

**Comment by orischwartz** [comment]
Nobody loves the inclusion of connect_vbms, let's not forget to remove that when they rewrite.

**Pull request merged**
